version: '3.8'

services:
  # FastAPI 应用服务
  api:
    image: python_env_fastapi:202509
    container_name: fastapi-app
    # 将服务加入自定义网络
    ports:
      - "9000:8000"
    # 覆盖 Dockerfile 中的工作目录
    volumes:
      # 将当前目录下的所有文件挂载到容器的 /app 目录
      - .:/app
      - "/home/carenk/my_data/01_projects/04_isra/02_fastapi/mnt/images:/data_mount"

  # 使用 command 关键字覆盖 Dockerfile 中的 CMD
    # 这里我们让应用监听 9000 端口
    command: ["uvicorn", "main_korean:app", "--host", "0.0.0.0", "--port", "8000"]

    networks:
      - network_docker_common_nginxuse



# 定义一个自定义网络
networks:
  network_docker_common_nginxuse:
    external: true
